# .github/workflows/java-ant-ci.yml
name: Java CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 24 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'      # <-- Cambiado a 24

      - name: Install Ant
        run: |
          sudo apt-get update
          sudo apt-get install -y ant
          ant -version

      - name: Build with Ant
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          ant -noinput -buildfile build.xml
